# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sum.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 238)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnSum = QtWidgets.QPushButton(self.centralwidget)
        self.btnSum.setGeometry(QtCore.QRect(150, 100, 89, 25))
        self.btnSum.setObjectName("btnSum")
        self.btnSum.clicked.connect(self.OnbtnSumClicked)
        self.txtValue1 = QtWidgets.QTextEdit(self.centralwidget)
        self.txtValue1.setGeometry(QtCore.QRect(70, 60, 121, 31))
        self.txtValue1.setObjectName("txtValue1")
        self.txtValue2 = QtWidgets.QTextEdit(self.centralwidget)
        self.txtValue2.setGeometry(QtCore.QRect(210, 60, 121, 31))
        self.txtValue2.setObjectName("txtValue2")
        self.lblSum = QtWidgets.QLabel(self.centralwidget)
        self.lblSum.setGeometry(QtCore.QRect(350, 70, 67, 17))
        self.lblSum.setObjectName("lblSum")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 470, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSum.setText(_translate("MainWindow", "Sum"))
        self.lblSum.setText(_translate("MainWindow", "0"))

    def OnbtnSumClicked(self):
        print ("I am clicked")
        s = int(self.txtValue1.toPlainText()) + int(self.txtValue2.toPlainText())
        self.lblSum.setText(str(s))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

# import sys
# from PyQt5.QtCore import *
# from PyQt5.QtGui import *
# from PyQt5.QtWidgets import *

# def window():
#    app = QApplication(sys.argv)
#    win = QDialog()
#    b1 = QPushButton(win)
#    b1.setText("Button1")
#    b1.move(50,20)
#    b1.clicked.connect(b1_clicked)
   
#    b2 = QPushButton(win)
#    b2.setText("Button2")
#    b2.move(50,50)
#    b2.clicked.connect(b2_clicked)
   
#    win.setGeometry(100,100,200,100)

#    win.setWindowTitle("PyQt5")
#    win.show()
#    sys.exit(app.exec_())

# def b1_clicked():
#    print ("Button 1 clicked")

# def b2_clicked():
#    print ("Button 2 clicked")

# if __name__ == '__main__':
#    window()